language: node_js
node_js:
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
  - "iojs"
install:
  - npm install
after_script:
  - codeclimate-test-reporter < report/node/lcov.info
script:
  - npm test
